/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/character/model.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Character(props) {
    const group = React.useRef();
    const { scene, animations } = useGLTF("./models/character/model.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name='AuxScene'>
                <group name='AuxScene_1'>
                    <group name='AuxScene_2'>
                        <group position={[0, -66.419, 4.97]}>
                            <primitive object={nodes.mixamorigHips} />
                            <skinnedMesh name='Ch14' geometry={nodes.Ch14.geometry} material={materials.Ch14_Body} skeleton={nodes.Ch14.skeleton} />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("./models/character/model.glb");
