name: 3d front Project

# trigger가 되는 브랜치명 및 액션(push)
on:
  push:
    branches:
      - master

# 위 이벤트가 트리거되면 실행할 목록
jobs:
  build:
    name: react build & deploy
    # runner가 실행될 환경 지정
    runs-on: ubuntu-latest

   # named은 단계별로 실행되는 액션들의 설명을 담은 것으로, 나중에 github action에서 workflow에 표시된다.
   # uses 키워드로 action을 불러옴
    steps:
      - name: checkout Github Action
        uses: actions/checkout@v3
        
      - name: check Node v
        run: node -v

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      # s3에 build 파일을 올린다.
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        run: 
          aws s3 cp --recursive --region ap-northeast-2 ./build s3://${{ secrets.AWS_S3_BUCKET  }
      
